car_env/blog/urls.py
from django.urls import path
from .views import BlogHomeView, BlogPostView

app_name = 'blog'

urlpatterns = [
    path('', BlogHomeView, name='home'),
    path('<int:id>', BlogPostView, name='post'),
]

car_env/customadmin/urls.py
from django.urls import path
from . import views

app_name = 'customadmin'

urlpatterns = [
    path('', views.HomeView, name='home'),

    # Main Page Urls
    path('general/', views.GeneralModelsView, name='general'),
    path('cities/update/', views.UpdateCityView, name='cities_update'),
    path('testimonial/add/', views.AddTestimonialView, name='testimonial_add'),
    path('testimonial/edit/<int:id>/', views.EditTestimonialView, name='testimonial_edit'),
    path('testimonial/delete/<int:id>/', views.DeleteTestimonialView, name='testimonial_delete'),
    path('home-page-banners/add/', views.AddMainPageBannersView, name='banner_add'),
    path('home-page-banners/edit/<int:id>/', views.EditMainPageBannersView, name='banner_edit'),
    path('home-page-banners/delete/<int:id>/', views.DeleteMainPageBannersView, name='banner_delete'),
    path('update-faqs/', views.UpdateFAQsView, name='update_faqs'),
    path('update-t&c/', views.UpdateTermsAndConditionsView, name='update_tnc'),

    path('contact-us/', views.ContactUsView, name='contact_us'),
    path('payments/', views.PaymentsView, name='payments'),

    # Ride Bookings Urls
    path('cancelled-rides/', views.CancelledRidesView, name='cancelled_rides'),
    path('booked-rides/', views.BookedRidesView, name='booked_rides'),
    path('assign-vendor-rides/', views.AssignVendorRidesView, name='assign_vendor_rides'),
    path('upcoming-rides/', views.UpcomingRidesView, name='upcoming_rides'),
    path('ongoing-rides/', views.OngoingRidesView, name='ongoing_rides'),
    path('completed-rides/', views.CompletedRidesView, name='completed_rides'),
    path('user-cancelled-rides/', views.UserCancelledRides, name='user_cancelled_rides'),
    path('vendor-cancelled-rides/', views.UserCancelledRides, name='vendor_cancelled_rides'),

    path('assign-vendors/<int:id>/', views.AssignVendorsView, name='assign_vendors'),
    path('vendor-bids/<int:id>/', views.UpdateVendorBidsView, name='vendor_bids'),
    path('assign-final-vendor/<int:id>/', views.AssignFinalVendorView, name='assign_final_vendor'),
    path('assign-driver-car/<int:id>/', views.AssignDriverCarView, name='assign_driver_car'),
    path('start-ride/<int:id>/', views.StartRideView, name='start_ride'),
    path('end-ride/<int:id>/', views.EndRideView, name='end_ride'),
    path('verify-ride/<int:id>/', views.VerifyRideView, name='verify_ride'),

    path('final-ride-details/', views.FinalRideDetailsView, name='final_ride_details'),

    # Popular Destinations Urls
    path('popular-destinations/', views.PopularDestinationsView, name = 'popular_destinations'),
    path('popular-destinations/add/', views.AddPopularDestinationView, name = 'popular_destinations_add'),
    path('popular-destinations/edit/<int:id>/', views.EditPopularDestinationView, name = 'popular_destinations_edit'),
    path('popular-destinations/delete/<int:id>/', views.DeletePopularDestinationView, name = 'popular_destinations_delete'),

    # Car Type Urls
    path('car-type/', views.CarTypePageViews, name='car_type'),
    path('update-car-attributes/', views.UpdateCarAttributes, name='update_car_attributes'),
    path('update-car-attribute-values/', views.UpdateCarAttributeValueView, name='update_car_attribute_values'),
    path('update-ride-additional-choices/', views.UpdateRideAdditionalChoices, name='update_ride_additional_choices'),
    path('update-city-ride-attributes/', views.UpdateCityRideAttributeValues, name='update_city_ride_attributes'),

    # Blog Urls
    path('blogs/',views.BlogsView, name="blogs"),
    path('update-categories/', views.UpdateBlogCategoriesView, name="update_categories"),
    path('post/add/',views.AddBlogPostView, name="post_add"),
    path('post/edit/<int:id>/',views.EditBlogPostView, name="post_edit"),
    path('post/delete/<int:id>/',views.DeleteBlogPostView, name="post_delete"),
    path('post/delete-comment/<int:id>/',views.DeleteBlogPostCommentView, name="post_comment_delete"),

    # Customer Urls
    path('customers/',views.CustomersView, name="customers"),
    path('customers/add/',views.AddCustomerView, name="customer_add"),
    path('customers/edit/<int:id>/',views.EditCustomerView, name="customer_edit"),
    path('customers/delete/<int:id>/',views.DeleteCustomerView, name="customer_delete"),

    path('promotional/update/<int:id>/', views.UpdateCustomerPromotionalView, name="customer_update_promotional"),

    # Vendor Urls
    path('vendors/',views.VendorsView, name="vendors"),
    path('vendor/<int:id>/',views.VendorView, name="vendor"),
    path('vendor/add/',views.VendorsView, name="vendor_add"),
    path('vendor/update-status/<int:id>/',views.UpdateVendorStatusView, name="vendor_update_status"),
    path('vendor/edit/<int:id>/',views.EditVendorView, name="vendor_edit"),
    path('vendor/delete/<int:id>/',views.DeleteVendorView, name="vendor_delete"),
    # path('vendor/cars/update/<int:id>/', views.UpdateVendorCarsView, name="vendor_cars_update"),
    # path('vendor/drivers/update/<int:id>/', views.UpdateVendorDriversView, name="vendor_drivers_update"),
    path('vendor/bank-details/update/<int:id>/', views.UpdateVendorBankDetailsView, name="vendor_banks_update"),
    path('vendor/car/add/<int:id>/', views.AddVendorCarView, name="vendor_car_add"),
    path('vendor/car/edit/<int:id>/', views.EditVendorCarView, name="vendor_car_edit"),
    path('vendor/car/delete/<int:id>/', views.DeleteVendorCarView, name="vendor_car_delete"),
    path('vendor/driver/add/<int:id>/', views.AddVendorDriver, name="vendor_driver_add"),
    path('vendor/driver/edit/<int:id>/', views.EditVendorDriver, name="vendor_driver_edit"),
    path('vendor/driver/delete/<int:id>/', views.DeleteVendorDriver, name="vendor_driver_delete"),

    # Test Views
    path('test/1/', views.TestView1, name='test1'),
    path('test/2/', views.TestView2, name='test2'),
    path('test/3/', views.TestView3, name='test3'),
    path('test/4/', views.TestView4, name='test4'),
    path('test/5/', views.TestView5, name='test5'),
    path('dashboard/', views.DashboardView , name='dashboard'),
    path('assign-vendors/<int:id>/', views.AssignVendorsView , name='assign_vendor'),
    path('assign-final-vendor/<int:id>/', views.AssignFinalVendorView , name='assign_final_vendor'),
]

car_env/taxotaxi/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('vendor/', include('vendor.urls', namespace='vendor')),
    path('driver/', include('driver.urls', namespace='driver')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('custom-admin/', include('customadmin.urls', namespace='customadmin')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

car_env/customadmin/models.py
from django.db import models

# Create your models here.

car_env/customadmin/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from django.forms import modelformset_factory, inlineformset_factory
from django.shortcuts import get_list_or_404, get_object_or_404
import requests, datetime
from django.contrib.auth import authenticate, login, logout
from django.db.models import Count


from . import models, forms
from core import models as coremodels
from blog import models as blogmodels
from customer import models as customermodels
from vendor import models as vendormodels


def HomeView(request):

    late_running_rides = coremodels.ride_booking.objects.filter(ride_status__in = ['Assigned Car/Driver'], pickup_datetime__lt =datetime.datetime.today())
    last_minute_rides = coremodels.ride_booking.objects.filter(ride_status__in = ['Assigned Car/Driver'], pickup_datetime__lt =(datetime.datetime.today()+datetime.timedelta(hours = 4)))
    upcoming_rides = coremodels.ride_booking.objects.filter(ride_status__in = ['Booked', 'Selected Vendors', 'Assigned Vendor'], pickup_datetime__lt =datetime.datetime.today())
    top_pickup_cities = coremodels.ride_booking.objects.values('pickup_city__name').order_by("-pickup_city__count").annotate(Count('pickup_city'))[:5]
    top_drop_cities = coremodels.ride_booking.objects.values('drop_city__name').order_by("-drop_city__count").annotate(Count('drop_city'))[:5]

    context = {
        'late_running_rides':late_running_rides,
        'last_minute_rides':last_minute_rides,
        'upcoming_rides':upcoming_rides,
        'top_drop_cities':top_drop_cities,
        'top_pickup_cities':top_pickup_cities,
    }
    return render(request, 'custom_admin/index.html',context)

def TestView1(request):
    context = {}
    return render(request, 'test/1.html',context)


def TestView2(request):
    context = {}
    return render(request, 'test/2.html',context)


def TestView3(request):
    context = {}
    return render(request, 'test/3.html',context)


def TestView4(request):
    context = {}
    return render(request, 'test/4.html',context)


def TestView5(request):
    context = {}
    return render(request, 'test/5.html',context)

# Ride Bookings View
def RideBookingView(request, id):
    booking = get_object_or_404(coremodels.ride_booking, id=id)
    context = {
        'booking':booking,
    }
    return render(request, 'ride_bookings/ride_booking.html', context)

def CancelledRidesView(request):
    bookings = coremodels.ride_booking.objects.filter(ride_status = 'Cancelled')
    context = {
        'bookings':bookings,
    }
    return render(request, 'ride_bookings/cancelled_rides.html', context)

def BookedRidesView(request):
    bookings = coremodels.ride_booking.objects.filter(ride_status = 'Booked')
    context = {
        'bookings':bookings,
    }
    return render(request, 'ride_bookings/booked_rides.html', context)

def AssignVendorRidesView(request):
    bookings = coremodels.ride_booking.objects.filter(ride_status = 'Selected Vendors')
    context = {
        'bookings':bookings,
    }
    return render(request, 'ride_bookings/assign_vendor_rides.html', context)

def UpdateVendorBidsView(request, id):
    booking = get_object_or_404(coremodels.ride_booking, id = id)
    BidsFormset = inlineformset_factory(coremodels.ride_booking, coremodels.vendorbids, extra=0, can_delete=False, exclude=['booking', 'datetime'])
    if request.method == 'POST':
        formset = BidsFormset(request.POST, instance = booking)
        if formset.is_valid():
            formset.save()
        return redirect('customadmin:assign_vendor_rides')
    else:
        formset = BidsFormset(instance = booking)
        context = {
            'formset':formset,
        }
        return render(request, 'ride_bookings/vendor_bids_formset.html', context)

def UpcomingRidesView(request):
    bookings = coremodels.ride_booking.objects.filter(ride_status__in = ['Assigned Vendor', 'Assigned Car/Driver'])
    late_bookings = coremodels.ride_booking.objects.filter(ride_status__in = ['Assigned Vendor', 'Assigned Car/Driver'], pickup_datetime__lt =datetime.datetime.today())
    context = {
        'bookings':bookings,
        'late_bookings':late_bookings,
    }
    return render(request, 'ride_bookings/upcoming_rides.html', context)

def OngoingRidesView(request):
    bookings = coremodels.ride_booking.objects.filter(ride_status__in = ['Ongoing', 'Completed'])
    context = {
        'bookings':bookings,
    }
    return render(request, 'ride_bookings/ongoing_rides.html', context)

def CompletedRidesView(request):
    bookings = coremodels.ride_booking.objects.filter(ride_status = 'Verified')
    context = {
        'bookings':bookings,
    }
    return render(request, 'ride_bookings/completed_rides.html', context)

def AssignVendorsView(request, id):
    booking = coremodels.ride_booking.objects.get(id=id)
    if request.method == 'POST':
        form = forms.AssignVendors(request.POST)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.booking = booking
            booking.ride_status = 'Selected Vendors'
            new_form.datetime = datetime.datetime.now()
            new_form.save()
            booking.save()
            form.save_m2m()
            # for vendor in new_form.vendors.all:
            #     vendorbid = coremodels.vendorbids.objects.create(booking=booking, vendor = vendor)
            #     vendorbid.max_bid = booking.ride_fare*(1-(new_form.commission/100))
            #     vendorbid.save()
        return redirect('customadmin:booked_rides')
    else:
        form = forms.AssignVendors()
        context = {
            'form':form,
        }
        return render(request, 'ride_bookings/assign_vendors_form.html', context)

def UserCancelledRides(request):
    bookings = coremodels.ride_booking.objects.filter(ride_status = 'User Cancelled')
    context = {
        'bookings':bookings,
    }
    return render(request, 'ride_bookings/user_cancelled_rides.html', context)

def VendorCancelledRides(request):
    bookings = coremodels.ride_booking.objects.filter(ride_status = 'Rejected')
    context = {
        'bookings':bookings,
    }
    return render(request, 'ride_bookings/vendor_cancelled_rides.html', context)

def AssignFinalVendorView(request, id):
    bid = get_object_or_404(coremodels.vendorbids, id=id)
    booking = bid.booking
    try:
        final_ride = coremodels.final_ride_detail.objects.get(booking = booking)
    except:
        final_ride = coremodels.final_ride_detail.objects.create(booking=booking, bid = bid)
    final_ride.save()
    booking.ride_status = "Assigned Vendor"
    booking.save()
    return redirect('customadmin:assign_vendor_rides')

def AssignDriverCarView(request, id):
    final_ride = get_object_or_404(coremodels.final_ride_detail, id= id)
    vendor = final_ride.bid.vendor
    cars = vendormodels.vendor_cars.objects.filter(vendor = vendor)
    drivers = vendormodels.driver.objects.filter(vendor = vendor)
    if request.method == 'POST':
        form = forms.AssignDriverCar(request.POST, request.FILES, instance = final_ride)
        if form.is_valid():
            form.save()
            final_ride.booking.ride_status = "Assigned Car/Driver"
            final_ride.booking.save()

            customer_message = "We have assigned Driver Name: " + str(final_ride.driver.full_name) + " (" + str(
                final_ride.driver.contact1) + ") " + "and Car Number: " + str(final_ride.car.registration_no)
            print(str(booking.phone_no), customer_message)

            driver_message = "You have been assigned to " + str(booking.name) + " (" + str(
                booking.phone_no) + " ) for " + str(booking.ride_type) + " ride, on dated " + str(
                booking.pickup_datetime) + " from " + str(booking.pickup_city) + " to " + str(booking.drop_city)
            print(str(final_ride.driver.contact1), driver_message)

        return redirect('customadmin:upcoming_rides')
    else:
        form = forms.AssignDriverCar(instance = final_ride)
        form.fields['car'].queryset = cars
        form.fields['driver'].queryset = drivers
        context = {
            'form':form,
        }
        return render(request, 'ride_bookings/assign_driver_car_form.html', context=context)

def StartRideView(request, id):
    final_ride = get_object_or_404(coremodels.final_ride_detail, id=id)
    vendor = final_ride.bid.vendor
    cars = vendormodels.vendor_cars.objects.filter(vendor=vendor)
    drivers = vendormodels.driver.objects.filter(vendor=vendor)
    if request.method == 'POST':
        form = forms.FinalRideForm(request.POST, request.FILES, instance=final_ride)
        if form.is_valid():
            form.save()
            final_ride.start_datetime = timezone.now()
            final_ride.booking.ride_status = "Ongoing"
            final_ride.booking.save()
            final_ride.save()
        return redirect('customadmin:upcoming_rides')
    else:
        form = forms.FinalRideForm(instance=final_ride)
        form.fields['car'].queryset = cars
        form.fields['driver'].queryset = drivers
        context = {
            'form': form,
        }
        return render(request, 'ride_bookings/start_ride_form.html', context=context)


def EndRideView(request, id):
    final_ride = get_object_or_404(coremodels.final_ride_detail, id=id)
    vendor = final_ride.bid.vendor
    cars = vendormodels.vendor_cars.objects.filter(vendor=vendor)
    drivers = vendormodels.driver.objects.filter(vendor=vendor)

    if request.method == 'POST':
        form = forms.FinalRideForm(request.POST, request.FILES, instance=final_ride)
        if form.is_valid():
            form.save()

car_env/customadmin/templates/car_type/index.html
{% extends 'admin_base.html' %}
{% load static %}
{% load template_tag %}

{% block extra_stylesheet %}

{% endblock extra_stylesheet %}
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet">
<style>
    body{
        font-family: 'Poppins', sans-serif;
    }
    
</style>


{% block content %}
<div class="main-content">
    <div class="page-content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-8">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">
                                Car Type Attributes
                                <a href="{% url 'customadmin:update_car_attribute_values' %}">
                                    <button type="button" style="float: right;" class="btn btn-success waves-effect waves-light mb-2">
                                        <i class="bx bx-add-to-queue font-size-16 align-middle"></i> Update Values
                                    </button>
                                </a>
                                <a href="{% url 'customadmin:update_car_attributes' %}">
                                    <button type="button" style="float: right; padding-right: 10px;margin-right: 10px;" class="btn btn-warning waves-effect waves-light mb-2">
                                        <i class="bx bx-add-to-queue font-size-16 align-middle"></i> Update Attributes
                                    </button>
                                </a>
                            </h4>

                            <table id="datatable" class="table table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    {% for car_type in car_types %}
                                        <th>{{ car_type.name }}</th>
                                    {% endfor %}
                                </tr>
                                </thead>
                                <tbody>
                                {% for car_attr in car_attrs %}
                                <tr>
                                    <td>{{ car_attr.name }}</td>
                                    {% for car_type in car_types %}
                                        <td>{{ car_type|car_attr_value:car_attr }}</td>
                                    {% endfor %}
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div> <!-- end col -->

                <div class="col-4">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">
                                    Ride Additional Choices
                                    <a href="{% url 'customadmin:update_ride_additional_choices' %}">
                                        <button type="button" style="float: right;" class="btn btn-success waves-effect waves-light mb-2">
                                            <i class="bx bx-add-to-queue font-size-16 align-middle"></i> Update
                                        </button>
                                    </a>
                                </h4>

                                <table id="datatable" class="table table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Name</th>
                                        <th>Value</th>
                                        <th>Ride Types</th>

                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for ride_additional_choice in ride_additional_choices %}
                                        <tr>
                                            <td>{{ forloop.counter }}</td>
                                            <td>{{ ride_additional_choice.name }}</td>
                                            <td>{{ ride_additional_choice.value }}</td>
                                            <td>
                                            {% for ride_type in ride_additional_choice.ride_type.all %}
                                                {{ ride_type.name }},
                                            {% endfor %}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div> <!-- end col -->
            </div> <!-- end row -->


            <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">
                                    City Ride Attributes
                                    <a href="{% url 'customadmin:update_city_ride_attributes' %}">
                                        <button type="button" style="float: right;" class="btn btn-success waves-effect waves-light mb-2">
                                            <i class="bx bx-add-to-queue font-size-16 align-middle"></i> Update
                                        </button>
                                    </a>
                                </h4>

                                <table id="datatable" class="table table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        {% for pickup_city in pickup_cities %}
                                            <th>{{ pickup_city.name }}</th>
                                        {% endfor %}
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for drop_city in drop_cities %}
                                    <tr>
                                        <td>{{ drop_city.name }}</td>
                                        {% for pickup_city in pickup_cities %}
                                            <td>

                                                <form method="get" action="{% url 'customadmin:update_city_ride_attributes' %}">
                                                    <input type="checkbox" class="custom-control-input" name="pickup_cities" value="{{ pickup_city.id }}" checked hidden>
                                                    <input type="checkbox" class="custom-control-input" name="drop_cities" value="{{ drop_city.id }}" checked hidden>

                                                    <button type="submit" style="float: right;" class="btn btn-warning waves-effect waves-light mb-2">
                                                        <i class="bx bx-add-to-queue font-size-16 align-middle"></i> Update
                                                    </button>
                                                </form>

                                            </td>
                                        {% endfor %}
                                    </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div> <!-- end col -->
            </div> <!-- end row -->



        </div>
    </div>
</div>

{% endblock content %}




{% block extra_scripts %}
<script>
    $(document).ready(function(){
        $("#customCheck1").click(function(){
            if($(this).prop("checked") == true){
                $("#customCheck1a").prop("checked",true);
                $("#customCheck1b").prop("checked",true);
                $("#customCheck1c").prop("checked",true);
                $("#customCheck1d").prop("checked",true);
                
            }
            else if($(this).prop("checked") == false){
                $("#customCheck1a").prop("checked",false);
                $("#customCheck1b").prop("checked",false);
                $("#customCheck1c").prop("checked",false);
                $("#customCheck1d").prop("checked",false);
            }
        });
        $("#customCheck2").click(function(){
            if($(this).prop("checked") == true){
                $("#customCheck2a").prop("checked",true);
                $("#customCheck2b").prop("checked",true);
                $("#customCheck2c").prop("checked",true);
                $("#customCheck2d").prop("checked",true);
                
            }
            else if($(this).prop("checked") == false){
                $("#customCheck2a").prop("checked",false);
                $("#customCheck2b").prop("checked",false);
                $("#customCheck2c").prop("checked",false);
                $("#customCheck2d").prop("checked",false);
            }
        });
        $("#customCheck3").click(function(){
            if($(this).prop("checked") == true){
                $("#customCheck3a").prop("checked",true);
                $("#customCheck3b").prop("checked",true);
                $("#customCheck3c").prop("checked",true);
                
            }
            else if($(this).prop("checked") == false){
                $("#customCheck3a").prop("checked",false);
                $("#customCheck3b").prop("checked",false);
                $("#customCheck3c").prop("checked",false);
            }
        });
        $("#customCheck4").click(function(){
            if($(this).prop("checked") == true){
                $("#customCheck4a").prop("checked",true);
                $("#customCheck4b").prop("checked",true);
                $("#customCheck4c").prop("checked",true);
                
            }
            else if($(this).prop("checked") == false){
                $("#customCheck4a").prop("checked",false);
                $("#customCheck4b").prop("checked",false);
                $("#customCheck4c").prop("checked",false);
            }
        });
    });
</script>
{% endblock extra_scripts %}