car_env/blog/urls.py
from django.urls import path
from .views import BlogHomeView, BlogPostView

app_name = 'blog'

urlpatterns = [
    path('', BlogHomeView, name='home'),
    path('<int:id>', BlogPostView, name='post'),
]

car_env/customadmin/urls.py
from django.urls import path
from . import views

app_name = 'customadmin'

urlpatterns = [
    path('', views.HomeView, name='home'),

    # Main Page Urls
    path('general/', views.GeneralModelsView, name='general'),
    path('cities/update/', views.UpdateCityView, name='cities_update'),
    path('testimonial/add/', views.AddTestimonialView, name='testimonial_add'),
    path('testimonial/edit/<int:id>/', views.EditTestimonialView, name='testimonial_edit'),
    path('testimonial/delete/<int:id>/', views.DeleteTestimonialView, name='testimonial_delete'),
    path('home-page-banners/add/', views.AddMainPageBannersView, name='banner_add'),
    path('home-page-banners/edit/<int:id>/', views.EditMainPageBannersView, name='banner_edit'),
    path('home-page-banners/delete/<int:id>/', views.DeleteMainPageBannersView, name='banner_delete'),
    path('update-faqs/', views.UpdateFAQsView, name='update_faqs'),
    path('update-t&c/', views.UpdateTermsAndConditionsView, name='update_tnc'),

    path('contact-us/', views.ContactUsView, name='contact_us'),
    path('payments/', views.PaymentsView, name='payments'),

    # Ride Bookings Urls
    path('cancelled-rides/', views.CancelledRidesView, name='cancelled_rides'),
    path('booked-rides/', views.BookedRidesView, name='booked_rides'),
    path('assign-vendor-rides/', views.AssignVendorRidesView, name='assign_vendor_rides'),
    path('upcoming-rides/', views.UpcomingRidesView, name='upcoming_rides'),
    path('ongoing-rides/', views.OngoingRidesView, name='ongoing_rides'),
    path('completed-rides/', views.CompletedRidesView, name='completed_rides'),
    path('user-cancelled-rides/', views.UserCancelledRides, name='user_cancelled_rides'),
    path('vendor-cancelled-rides/', views.UserCancelledRides, name='vendor_cancelled_rides'),

    path('assign-vendors/<int:id>/', views.AssignVendorsView, name='assign_vendors'),
    path('vendor-bids/<int:id>/', views.UpdateVendorBidsView, name='vendor_bids'),
    path('assign-final-vendor/<int:id>/', views.AssignFinalVendorView, name='assign_final_vendor'),
    path('assign-driver-car/<int:id>/', views.AssignDriverCarView, name='assign_driver_car'),
    path('start-ride/<int:id>/', views.StartRideView, name='start_ride'),
    path('end-ride/<int:id>/', views.EndRideView, name='end_ride'),
    path('verify-ride/<int:id>/', views.VerifyRideView, name='verify_ride'),

    path('final-ride-details/', views.FinalRideDetailsView, name='final_ride_details'),

    # Popular Destinations Urls
    path('popular-destinations/', views.PopularDestinationsView, name = 'popular_destinations'),
    path('popular-destinations/add/', views.AddPopularDestinationView, name = 'popular_destinations_add'),
    path('popular-destinations/edit/<int:id>/', views.EditPopularDestinationView, name = 'popular_destinations_edit'),
    path('popular-destinations/delete/<int:id>/', views.DeletePopularDestinationView, name = 'popular_destinations_delete'),

    # Car Type Urls
    path('car-type/', views.CarTypePageViews, name='car_type'),
    path('update-car-attributes/', views.UpdateCarAttributes, name='update_car_attributes'),
    path('update-car-attribute-values/', views.UpdateCarAttributeValueView, name='update_car_attribute_values'),
    path('update-ride-additional-choices/', views.UpdateRideAdditionalChoices, name='update_ride_additional_choices'),
    path('update-city-ride-attributes/', views.UpdateCityRideAttributeValues, name='update_city_ride_attributes'),

    # Blog Urls
    path('blogs/',views.BlogsView, name="blogs"),
    path('update-categories/', views.UpdateBlogCategoriesView, name="update_categories"),
    path('post/add/',views.AddBlogPostView, name="post_add"),
    path('post/edit/<int:id>/',views.EditBlogPostView, name="post_edit"),
    path('post/delete/<int:id>/',views.DeleteBlogPostView, name="post_delete"),
    path('post/delete-comment/<int:id>/',views.DeleteBlogPostCommentView, name="post_comment_delete"),

    # Customer Urls
    path('customers/',views.CustomersView, name="customers"),
    path('customers/add/',views.AddCustomerView, name="customer_add"),
    path('customers/edit/<int:id>/',views.EditCustomerView, name="customer_edit"),
    path('customers/delete/<int:id>/',views.DeleteCustomerView, name="customer_delete"),

    path('promotional/update/<int:id>/', views.UpdateCustomerPromotionalView, name="customer_update_promotional"),

    # Vendor Urls
    path('vendors/',views.VendorsView, name="vendors"),
    path('vendor/<int:id>/',views.VendorView, name="vendor"),
    path('vendor/add/',views.VendorsView, name="vendor_add"),
    path('vendor/update-status/<int:id>/',views.UpdateVendorStatusView, name="vendor_update_status"),
    path('vendor/edit/<int:id>/',views.EditVendorView, name="vendor_edit"),
    path('vendor/delete/<int:id>/',views.DeleteVendorView, name="vendor_delete"),
    # path('vendor/cars/update/<int:id>/', views.UpdateVendorCarsView, name="vendor_cars_update"),
    # path('vendor/drivers/update/<int:id>/', views.UpdateVendorDriversView, name="vendor_drivers_update"),
    path('vendor/bank-details/update/<int:id>/', views.UpdateVendorBankDetailsView, name="vendor_banks_update"),
    path('vendor/car/add/<int:id>/', views.AddVendorCarView, name="vendor_car_add"),
    path('vendor/car/edit/<int:id>/', views.EditVendorCarView, name="vendor_car_edit"),
    path('vendor/car/delete/<int:id>/', views.DeleteVendorCarView, name="vendor_car_delete"),
    path('vendor/driver/add/<int:id>/', views.AddVendorDriver, name="vendor_driver_add"),
    path('vendor/driver/edit/<int:id>/', views.EditVendorDriver, name="vendor_driver_edit"),
    path('vendor/driver/delete/<int:id>/', views.DeleteVendorDriver, name="vendor_driver_delete"),

    # Test Views
    path('test/1/', views.TestView1, name='test1'),
    path('test/2/', views.TestView2, name='test2'),
    path('test/3/', views.TestView3, name='test3'),
    path('test/4/', views.TestView4, name='test4'),
    path('test/5/', views.TestView5, name='test5'),
    path('dashboard/', views.DashboardView , name='dashboard'),
    path('assign-vendors/<int:id>/', views.AssignVendorsView , name='assign_vendor'),
    path('assign-final-vendor/<int:id>/', views.AssignFinalVendorView , name='assign_final_vendor'),
]

car_env/driver/urls.py
from django.urls import path
from . import views
app_name = 'driver'

urlpatterns = [
    path('', views.DashboardView, name='dashboard'),

    path('upcoming/', views.UpcomingRidesView, name='upcoming'),
    path('payments/', views.PaymentsView, name='payments'),
    path('booking-history/', views.BookingsHistoryView, name='booking_history'),

    path('ride-detail/', views.RideDetailsView, name='booking_detail'),
    path('ride-detail/start/<int:id>/', views.StartRideView, name='start_ride'),
    path('ride-detail/end/<int:id>/', views.EndRideView, name='end_ride'),
    path('map/',views.map ,name='map'),
]

car_env/taxotaxi/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('vendor/', include('vendor.urls', namespace='vendor')),
    path('driver/', include('driver.urls', namespace='driver')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('custom-admin/', include('customadmin.urls', namespace='customadmin')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

car_env/customadmin/models.py
from django.db import models

# Create your models here.

car_env/driver/models.py
from django.db import models

# Create your models here.

car_env/driver/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from . import models
from vendor import models as vendormodels
from core import models as coremodels



class DriverProfileForm(forms.ModelForm):
    class Meta:
        model = vendormodels.driver
        exclude = ['vendor', 'status']

    # def clean_contact1(self):
    #     mobile = self.cleaned_data.get('contact1')
    #     if mobile:
    #         try:
    #             user = coremodels.User.objects.get(username = mobile)
    #             raise forms.ValidationError('Mobile Number is already registered')
    #         except:
    #             return mobile


class FinalRideForm(forms.ModelForm):
    class Meta:
        model = coremodels.final_ride_detail
        fields = ['initial_odometer_reading', 'final_odometer_reading', 'other_charges', 'collected_amount']

car_env/driver/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from django.forms import modelformset_factory, inlineformset_factory

import datetime
from . import models, forms
from vendor import models as vendormodels
from core import models as coremodels

import requests
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import get_user_model

def SMS(mobile, message):
    mobile = '230' + str(mobile)
    message = str(message)
    url = 'https://www.smsgatewayhub.com/api/mt/SendSMS?APIKey=fsdCr1FyckqYrndE63halg&senderid=SMSTST&channel=2&DCS=0&flashsms=0&number='+mobile+'&text='+message+'&route=1'
    print(url)
    r = requests.post(url = url)
    x = r.text
    print(x)

@login_required(login_url='/login/')
def DashboardView(request):
    # try:
        driver_profile = get_object_or_404(vendormodels.driver, user = request.user)

        if request.method == 'POST':
            type = request.POST['type']
            if type == 'profile':
                profile_form = forms.DriverProfileForm(request.POST, request.FILES, instance=driver_profile)
                if profile_form.is_valid():
                    profile_form.save()
                    messages.success(request, 'Details Saved Successfully',
                                     extra_tags='alert alert-success alert-dismissible')
                    return redirect('driver:dashboard')
                else:
                    messages.success(request, 'Please Update Details Correctly',
                                     extra_tags='alert alert-danger alert-dismissible')
                    context = {
                        'profile_form': profile_form,
                        'driver': driver_profile,
                    }
                    return render(request, 'Driver/profile.html', context)
            elif type == 'change_password':
                password = request.POST['current_password']
                new_password = request.POST['new_password']
                user = authenticate(username=request.user.username, password=password)
                if user is not None:
                    user.set_password(new_password)
                    user.save()
                    login(request, user)
                    messages.success(request, 'Password Updated', extra_tags='alert alert-success alert-dismissible')
                    return redirect('driver:dashboard')
                else:
                    messages.error(request, 'Invalid Password', extra_tags='alert alert-error alert-dismissible')
        else:
            profile_form = forms.DriverProfileForm(instance=driver_profile)

            context = {
                'profile_form':profile_form,
                'driver':driver_profile,
            }
            print("#--------------------------------------------------------------------------#")
            return render(request, 'Driver/profile.html', context)
    # except:
    #     print("WHY")
    #     return redirect('core:dashboard')

def UpcomingRidesView(request):
    driver = vendormodels.driver.objects.get(user=request.user)
    final_rides = coremodels.final_ride_detail.objects.filter(driver = driver).filter(booking__ride_status__in = ["Assigned Car/Driver"] )
    form = forms.FinalRideForm()
    context = {
        'final_rides':final_rides,
        'form':form,
    }
    return render(request, 'Driver/ride_detail.html', context)

def RideDetailsView(request):
    driver = vendormodels.driver.objects.get(user=request.user)
    final_rides = coremodels.final_ride_detail.objects.filter(driver = driver).filter(booking__ride_status__in = ["Ongoing"] )
    form = forms.FinalRideForm()
    context = {
        'final_rides':final_rides,
        'form':form,
    }
    return render(request, 'Driver/ride_detail.html', context)

def StartRideView(request, id):
    if request.method == "POST":
        final_ride = get_object_or_404(coremodels.final_ride_detail, id=id)
        form = forms.FinalRideForm(request.POST, instance = final_ride )
        if form.is_valid():
            form.save()
            final_ride.start_datetime = datetime.datetime.now()
            booking = final_ride.booking
            booking.ride_status = "Ongoing"
            final_ride.save()
            booking.save()
            messages.success(
                request,
                'Ride Started',
                extra_tags='alert alert-success alert-dismissible'
            )
            return redirect('driver:booking_detail')
        else:
            print(form.errors)
            messages.error(
                request,
                'Please Fill Details Correctly',
                extra_tags='alert alert-danger alert-dismissible'
            )
            return redirect('driver:booking_detail')

def EndRideView(request, id):
    if request.method == "POST":
        final_ride = get_object_or_404(coremodels.final_ride_detail, id=id)
        form = forms.FinalRideForm(instance = final_ride)
        if form.is_valid():
            form.save()
            final_ride.end_datetime = datetime.datetime.now()
            booking = final_ride.booking
            booking.ride_status = "Completed"
            final_ride.save()
            booking.save()
            messages.success(
                request,
                'Ride Ended',
                extra_tags='alert alert-success alert-dismissible'
            )
            return redirect('driver:booking_detail')
        else:
            messages.error(
                request,
                'Please Fill Details Correctly',
                extra_tags='alert alert-danger alert-dismissible'
            )
            return redirect('driver:booking_detail')

def RejectBookingView(request, id):
    if request.method == "POST":

        final_ride = get_object_or_404(coremodels.final_ride_detail, id=id)

        rejection_reason = request.POST['rejection_reason']
        bid = final_ride.bid
        bid.rejection_reason = rejection_reason
        bid.save()

        booking = final_ride.booking
        booking.ride_status = "Booked"
        booking.save()

        booking.assign_vendor.delete()
        final_ride.delete()

        messages.success(
            request,
            'Assignment Rejected',
            extra_tags='alert alert-success alert-dismissible'
        )
        return redirect('driver:assignments')

def BookingsHistoryView(request):
    driver = vendormodels.driver.objects.get(user= request.user)
    final_rides = coremodels.final_ride_detail.objects.filter(driver = driver, booking__ride_status = "Verified")
    # final_rides = coremodels.final_ride_detail.objects.all()
    context = {
        'final_rides':final_rides
    }
    return render(request, 'Driver/booking_history.html', context)

def PaymentsView(request):
    driver = vendormodels.driver.objects.get(user= request.user)
    final_rides = coremodels.final_ride_detail.objects.filter(driver = driver, booking__ride_status="Verified")
    context = {
        'final_rides': final_rides
    }
    return render(request,'Driver/payments.html' , context)


def BookingsView(request):
    driver = vendormodels.driver.objects.get(user= request.user)
    bookings = coremodels.ride_booking.objects.filter(ride_status = "Selected Vendors", final_ride__driver = driver)

    if "sort" in request.GET:
        sort = request.GET["sort"]
        if sort.lower() == "date":
            bookings = bookings.order_by('-pickup_datetime')
        else:
            bookings = bookings.order_by('id')


    context = {
        "bookings":bookings,
    }
    return render(request, 'Driver/bookings.html', context)


def AssignmentsView(request):
    vendor = models.vendorprofile.objects.get(user=request.user)
    final_rides = coremodels.final_ride_detail.objects.filter(bid__vendor = vendor).filter(booking__ride_status = "Assigned Vendor" )
    context = {
        'final_rides':final_rides
    }
    return render(request, 'Vendor/assignments.html', context)

def map(request):
    context = None
    return render(request,'Driver/map.html', context)

car_env/customadmin/templates/vendors/index.html
{% extends 'admin_base.html' %}
{% load static %}


{% block extra_stylesheet %}
<style>
    .hidden{
        display: none;
    }
</style>
{% endblock extra_stylesheet %}



{% block content %}
<div class="main-content">

    <div class="page-content">
        <div class="container-fluid">

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box d-flex align-items-center justify-content-between">
                        <h4 class="mb-0 font-size-18">Vendor Tables</h4>

                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="javascript: void(0);">Tables</a></li>
                                <li class="breadcrumb-item active">Vendor Tables</li>
                            </ol>
                        </div>

                    </div>
                </div>
            </div>
            <!-- end page title -->

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">

                            <h4 class="card-title">Vendor Details
                                <button type="button" style="float: right;" class="btn btn-success waves-effect waves-light mb-2">
                                    <i class="bx bx-add-to-queue font-size-16 align-middle"></i> Add
                                </button>
                            </h4>
                            <p class="card-title-desc">
                            </p>
                            <div class="table-responsive">
                                <table id="" class="table table-striped table-bordered nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100% !important;">
                                <thead>
                                <tr>
                                    <th></th>
                                    <th>Name</th>
                                    
                                    <th>Mobile</th>
                                    <th>Alternate Mobile</th>
                                    <th>Email</th>
                                    <th>Company Name</th>
                                    <th>Status</th>
                                    <th></th>
                                    
                                </tr>
                                </thead>


                                <tbody>
                                {% for vendor in vendors %}
                                <tr>
                                    <td><input type="radio" name="vendors" value="vendor-{{ vendor.id }}" onclick="DisplayFunc(this)"></td>
                                    <td>{{ vendor.full_name }}</td>
                                    
                                    <td>{{ vendor.user.mobile }}</td>
                                    <td>{{ vendor.contact2 }}</td>
                                    <td>{{ vendor.email }}</td>
                                    <td>{{ vendor.company_name }}</td>
                                    <td>{{ vendor.status }}</td>

                                    <td>
                                        <div style="display: flex;">
                                        <a href="{% url 'customadmin:vendor' vendor.id %}">
                                            <i class="bx bx-show font-size-16 align-middle"></i>
                                        </a>
                                        <a href="{% url 'customadmin:vendor_update_status' vendor.id %}">
                                            <i class="bx bx-check-square font-size-16 align-middle"></i>
                                        </a>
                                        <a href="{% url 'customadmin:vendor_edit' vendor.id %}">
                                            <i class="bx bx-edit-alt font-size-16 align-middle"></i>
                                        </a>
                                        <a href="{% url 'customadmin:vendor_edit' vendor.id %}">
                                            <i class="bx bxs-trash font-size-16 align-middle"></i>
                                        </a>
                                        </div>
                                    </td>
                                </tr>

                                {% endfor %}
                         
                              
                                </tbody>
                            </table>
                        </div>
                        </div>
                    </div>
                </div> <!-- end col -->
            </div> <!-- end row -->

        {% for vendor in vendors %}

            <div class="row vendor-details" id="vendor-{{ vendor.id }}" style="display: none">


            <div class="row">
                <div class="col-6">

                    <div class="card">
                        <div class="card-body">

                            <h4 class="card-title">Vendor Cars
                                <a href="{% url 'customadmin:vendor_car_add' vendor.id %}">
                                    <button type="button" style="float: right;" class="btn btn-primary waves-effect waves-light mb-2">
                                        <i class="bx bx-add-to-queue font-size-16 align-middle"></i> Add
                                    </button>
                                </a>
                            </h4>
                            <p class="card-title-desc">
                            </p>
                            <div class="table-responsive">
                                <table id="" class="table table-striped table-bordered nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100% !important;">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Car Type</th>
                                        <th>Owner Name</th>
                                        <th>Registration Number</th>
                                        <th>Date of Registration</th>
                                        <th>Status</th>
                                        <th></th>

                                    </tr>
                                    </thead>

                                    <tbody>
                                    {% for car in vendor.vendor_cars_set.all %}
                                        <tr>
                                            <td>{{ forloop.counter }}</td>
                                            <td>{{ car.car_type }}</td>
                                            <td>{{ car.owner_name }}</td>
                                            <td>{{ car.registration_no }}</td>
                                            <td>{{ car.dateofregistration }}</td>

                                            <td>{{ car.status }}</td>
                                            <td>
                                                <a href="{% url 'customadmin:vendor_car_edit' car.id %}">
                                                    <i class="bx bx-edit-alt font-size-16 align-middle"></i>
                                                </a>
                                                <a href="{% url 'customadmin:vendor_car_delete' car.id %}">
                                                    <i class="bx bxs-trash font-size-16 align-middle"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div> 
                <!-- end col -->
                <div class="col-6">
                    <div class="card">
                        <div class="card-body">

                            <h4 class="card-title">Drivers
                                <a href="{% url 'customadmin:vendor_driver_add' vendor.id %}">
                            <button type="button" style="float: right;" class="btn btn-primary mr-2 waves-effect waves-light mb-2">
                                <i class="bx bx-add-to-queue font-size-16 align-middle"></i> Add
                            </button></a>
                            </h4>
                            <p class="card-title-desc">
                            </p>
                            <div class="table-responsive">
                                <table id="" class="table table-striped table-bordered nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100% !important;">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Full Name</th>
                                    
                                    <th>Mobile</th>
                                    <th>Email</th>
                                    <th>Status</th>
                                    <th></th>
                                </tr>
                                </thead>


                                <tbody>
                                {% for driver in vendor.driver_set.all %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ driver.full_name }}</td>
                                    
                                    <td>{{ driver.contact1 }}</td>
                                    <td>{{ driver.email }}</td>

                                    <td>{{ driver.status }}</td>
                                    <td>
                                        <a href="{% url 'customadmin:vendor_driver_edit' driver.id %}">
                                            <i class="bx bx-edit-alt font-size-16 align-middle"></i>
                                        </a>
                                        <a href="{% url 'customadmin:vendor_driver_delete' driver.id %}">
                                            <i class="bx bxs-trash font-size-16 align-middle"></i>
                                        </a>
                                </tr>
                                {% endfor %}
                              
                                </tbody>
                            </table>
                        </div>
                        </div>
                    </div>
                </div>
            </div> 
        {% endfor %}

           <!-- end row -->

        </div> <!-- container-fluid -->
    </div>
    <!-- End Page-content -->

   
</div>
</div>


{% endblock content %}




{% block extra_scripts %}

<script>
    $(document).ready(function(){
        $('input[type=radio]').change(function(){
            $('.vendor-details').hide();
            id = $(this).val()
            str = '#' + id;
            $(str).show();
        });
    });
</script>
{% endblock extra_scripts %}

car_env/customadmin/templates/vendors/vendor_driver_formset.html
{% extends 'admin_base.html' %}
{% load static %}


{% block extra_stylesheet %}

{% endblock extra_stylesheet %}



{% block content %}

<div class="main-content">

    <div class="page-content">
        <div class="container-fluid">

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box d-flex align-items-center justify-content-between">
                        <h4 class="mb-0 font-size-18">Blog Categories Forms</h4>

                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="javascript: void(0);">Blogs</a></li>
                                <li class="breadcrumb-item active">Blog Categories Forms</li>
                            </ol>
                        </div>

                    </div>
                </div>
            </div>
            <!-- end page title -->

            <div class="row">
                <div class="col-6">
                    <div class="card">
                        <div class="card-body">

                            <h4 class="card-title"></h4>
                            <p class="card-title-desc"></p>
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {% for form in formset %}
                                    {{ form }}
                                    <br>
                                {% endfor %}
                                <input type="submit">
                            </form>
                        </div>
                    </div>
                </div> <!-- end col -->

            </div>
            <!-- end row -->

            <!-- end row -->

        </div> <!-- container-fluid -->
    </div>
    <!-- End Page-content -->

</div>


{% endblock content %}




{% block extra_scripts %}

{% endblock extra_scripts %}