car_env/blog/urls.py
from django.urls import path
from .views import BlogHomeView, BlogPostView

app_name = 'blog'

urlpatterns = [
    path('', BlogHomeView, name='home'),
    path('<int:id>', BlogPostView, name='post'),
]

car_env/core/urls.py
from django.urls import path
from . import views
app_name = 'core'

urlpatterns = [
    path('', views.HomeView, name='home'),

    path('coming-soon', views.ComingSoonView, name='coming_soon'),
    path('test/', views.TestView, name='test'),
    path('cars/', views.CarSpecificationsView, name='cars'),
    path('checkbox-adder/', views.CheckBoxesAdder, name='checkbox-adder'),
    

    path('faq/', views.FAQView, name='faq'),
    path('terms-and-conditions/', views.TermsAndConditionsView, name='terms&conditions'),
    path('contact-us/', views.ContactView, name='contact'),

    path('login/', views.LoginView, name='login'),
    path('register/otp-verification', views.RegisterOTPVerification, name='register_otp_verification'),
    path('logout/', views.LogoutView, name='logout'),

    path('forgot-password', views.ForgotPasswordView, name='forgot_password'),
    path('reset-password', views.ForgotPasswordOTPView, name='forgot_password_otp'),

    path('dashboard/', views.DashboardView, name='dashboard'),
    path('register-vendor-design/', views.RegisterVendorAgentView, name='register_vendor_agent'),

    path('populatedata/', views.populate_data, name='populatedata'),

    path('booking/login/', views.CustomerLoginView, name='booking-login'),
    path('booking/authentication/', views.CustomerAuthenticationView, name='booking-authentication'),
    path('booking/otp-verification/', views.OTPVerificationView, name='booking-otp-verification'),
    path('checkout/', views.CheckoutView, name='checkout'),
    path('checkout2/', views.checkout2, name='checkout2'),
    path('payment/', views.PaymentView, name='payment'),
    path('payu/success', views.payu_success, name='payu_success'),
    path('payu/failure', views.payu_failure, name='payu_failure'),

    path('api/booking',views.booking_view, name='booknow'),
]

car_env/taxotaxi/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('vendor/', include('vendor.urls', namespace='vendor')),
    path('driver/', include('driver.urls', namespace='driver')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('custom-admin/', include('customadmin.urls', namespace='customadmin')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

car_env/templates/base.html
{% load static %}

<!DOCTYPE html>
<html style="background-color: white;" lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="description" content="TaxoTaxi">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>TaxoTaxi</title>

        <!-- Css Files Start -->
		<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
		<link href="{% static 'css/style.css' %}" rel="stylesheet">
		<link href="{% static 'css/fontawesome-all.min.css' %}" rel="stylesheet">
		<link id="switcher" href="{% static 'css/color.css' %}" rel="stylesheet">
		<link href="{% static 'css/color-switcher.css' %}" rel="stylesheet">
		<link href="{% static 'css/owl.carousel.css' %}" rel="stylesheet">
		<link href="{% static 'css/animate.css' %}" rel="stylesheet">
		<link href="{% static 'css/responsive.css' %}" rel="stylesheet">
        <link href="{% static 'css/icomoon.css' %}" rel="stylesheet">
		<!-- Css Files End -->



        <!-- Favicon -->
        <link href="{% static 'images/logo2.png' %}" rel="shortcut icon"/>

        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

        {% block extra_stylesheet %}
        {% endblock extra_stylesheet %}

        <!--[if lt IE 9]>
	      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	    <![endif]-->
           <style type="text/css">
                .alert {
                  text-align: center;
                     display: flow-root;
                     margin: 0;
                     font-size: larger;
                  font-weight: bold;
                }
                .closebtn {
                  margin-left: 15px;
                  color: white !important;
                  font-weight: bold;
                  float: right;
                  font-size: 22px;
                  line-height: 20px;
                  cursor: pointer;
                  transition: 0.3s;
                }
                .closebtn:hover {
                  color: white !important;
                }
               .close{
                   color: #cdd3d8 !important;
               }
            </style>
    </head>



<body>

    <!--Wrapper Content Start-->
    <div class="tj-wrapper">
        <div class="loader-outer">
            <div class="tj-loader">
                <div class='loader loader2'>
                  <div>
                    <div>
                      <div>
                        <div>
                          <div>
                            <div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                {% comment %}
                <img src="{% static 'images/pre-loader.gif' %}" alt="">
                {% endcomment %}
                <h2>Loading...</h2>
            </div>
        </div>


    {% comment %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success" role="alert">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <strong>{{ message }}</strong>  &ensp;
                </div>
            {% endfor %}
        {% endif %}
    {% endcomment %}

	{% include "navbar.html" %}

    {% if messages %}
        {% for message in messages %}
            <div class="{{ message.tags }}">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong></strong> {{ message }}
            </div>
        {% endfor %}
    {% endif %}



    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock extra_body %}

    {% block footer %}
    {% include "footer.html" %}
    {% endblock footer %}

    </div>
    <!--Wrapper Content End-->

    {% include "scripts.html" %}
  
    {% block extra_scripts %}
    {% endblock extra_scripts %}

</body>
</html>

car_env/templates/booking_1.html
{% extends 'admin_base.html' %}
{% load static %}

car_env/templates/current_datetime.html
<html>
   <head onload="submitPayuForm()">
      <script type="text/javascript">
         var hash = "{{ hashh }}";
         function submitPayuForm() {
           if(hash =='') {
             return;
           }
           var payuForm = document.forms.payuForm;
           payuForm.submit();
         }
      </script>
   </head>
   <body>
      <h2>PayU Form</h2>
      <br/>
      {% if error %}
      <span style="color:red">Please fill all mandatory fields.</span>
      <br/>
      <br/>
      {% endif %}
      <form action={{ action }} method="post" name="payuForm">
         {% csrf_token %}
         <input type="hidden" name="key" value="{{ MERCHANT_KEY }}" />
         <input type="hidden" name="hash_string" value="{{ hash_string }}" />
         <input type="hidden" name="hash" value="{{ hashh }}"/>
         <input type="hidden" name="posted" value="{{ posted }}"/>
         <input type="hidden" name="txnid" value="{{ txnid }}" />
         <table>
            <tr>
               <td><b>Mandatory Parameters</b></td>
            </tr>
            <tr>
               <td>Amount: </td>
               <td><input name="amount" value="{{ posted.amount|default:'' }}" /></td>
               <td>First Name: </td>
               <td><input name="firstname" id="firstname" value="{{ posted.firstname|default:'' }}" /></td>
            </tr>
            <tr>
               <td>Email: </td>
               <td><input name="email" id="email" value="{{ posted.email|default:'' }}" /></td>
               <td>Phone: </td>
               <td><input name="phone" value="{{ posted.phone|default:'' }}" /></td>
            </tr>
            <tr>
               <td>Product Info: </td>
               <td colspan="3"><textarea name="productinfo">{{ posted.productinfo|default:'' }}</textarea></td>
            </tr>
            <tr>
               <td>Success URI: </td>
               <td colspan="3"><input name="surl" value="{{ posted.surl }}" size="64" /></td>
            </tr>
            <tr>
               <td>Failure URI: </td>
               <td colspan="3"><input name="furl" value="{{ posted.furl }}" size="64" /></td>
            </tr>
            <tr>
               <td colspan="3"><input type="hidden" name="service_provider" value="payu_paisa" size="64" /></td>
            </tr>
            <tr>
               <td><b>Optional Parameters</b></td>
            </tr>
            <tr>
               <td>Last Name: </td>
               <td><input name="lastname" id="lastname" value="{{ posted.lastname }}" /></td>
               <td>Cancel URI: </td>
               <td><input name="curl" value="" /></td>
            </tr>
            <tr>
               <td>Address1: </td>
               <td><input name="address1" value="{{ posted.address1 }}" /></td>
               <td>Address2: </td>
               <td><input name="address2" value="{{ posted.address2 }}" /></td>
            </tr>
            <tr>
               <td>City: </td>
               <td><input name="city" value="{{ posted.city }}" /></td>
               <td>State: </td>
               <td><input name="state" value="{{ posted.state }}" /></td>
            </tr>
            <tr>
               <td>Country: </td>
               <td><input name="country" value="{{ posted.country }}" /></td>
               <td>Zipcode: </td>
               <td><input name="zipcode" value="{{ posted.zipcode }}" /></td>
            </tr>
            <tr>
               <td>UDF1: </td>
               <td><input name="udf1" value="{{ posted.udf1 }}" /></td>
               <td>UDF2: </td>
               <td><input name="udf2" value="{{ posted.udf2 }}" /></td>
            </tr>
            <tr>
               <td>UDF3: </td>
               <td><input name="udf3" value="{{ posted.udf3 }}" /></td>
               <td>UDF4: </td>
               <td><input name="udf4" value="{{ posted.udf4 }}" /></td>
            </tr>
            <tr>
               <td>UDF5: </td>
               <td><input name="udf5" value="{{ posted.udf5 }}" /></td>
               <td>PG: </td>
               <td><input name="pg" value="{{ posted.PG }}" /></td>
            </tr>
            <td colspan="4"><input type="submit" value="Submit" /></td>
            </tr>
         </table>
      </form>
   </body>
</html>

car_env/templates/empty_templatew.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load fullurl %}

{% block extra_stylesheet %}

{% endblock extra_stylesheet %}



{% block content %}


{% endblock content %}




{% block extra_scripts %}

{% endblock extra_scripts %}

car_env/templates/footer.html
<!--Footer Content Start-->
<section class="tj-footer">
   <div class="container">
      <div class="row">
         <div class="col-md-6">
            <div class="about-widget widget">
               <h3>About Taxotaxi</h3>
               <p>Search for will uncover many web sites variables onto of passages of lorem ipsum available but the majority the words all predefined humour to met chunks recently with desktop.</p>
               <ul class="fsocial-links">
                  <li><a href="http://www.facebook.com"><i class="fab fa-facebook-f"></i></a></li>
                  <li><a href="http://www.twitter.com"><i class="fab fa-twitter"></i></a></li>
                  <li><a href="http://www.linkedin.com"><i class="fab fa-linkedin-in"></i></a></li>
                  <!-- <li><a href="http://www.pinterest.com"><i class="fab fa-pinterest-p"></i></a></li> -->
                  <li><a href="http://www.instagram.com"><i class="fab fa-instagram"></i></a></li>
               </ul>
            </div>
         </div>
         <div class="col-md-3">
            <div class="links-widget widget">
               <h3>Explore Links</h3>
               <ul class="flinks-list">
                  <!-- <li><i class="far fa-folder"></i><a href="">One Way</a></li>
                     <li><i class="far fa-folder"></i><a href="">Multi-Way/Round Trip</a></li> -->
                  <li><i class="far fa-folder"></i><a href="">About Us</a></li>
                  <li><i class="far fa-folder"></i><a href="{% url 'blog:home' %}">Blog</a></li>
                  <li><i class="far fa-folder"></i><a href="{% url 'core:faq' %}">F.A.Q.</a></li>
                  <li><i class="far fa-folder"></i><a href="{% url 'core:contact' %}">Contact-Us</a></li>
                  <li><i class="far fa-folder"></i><a href="{% url 'core:terms&conditions' %}"> Terms & conditions</a></li>
                  <!-- <li><i class="far fa-folder"></i><a href=""> Company Policy</a></li> -->
               </ul>
            </div>
         </div>
         <div class="col-md-3">
            <div class="contact-info widget">
               <h3>Contact Info</h3>
               <ul class="contact-box">
                  <li>
                     <i class="fas fa-home" aria-hidden="true"></i> Roches - Noires , MAURITIUS
                  </li>
                  <li>
                     <i class="far fa-envelope-open"></i>
                     <a href="mailto:aviramjeeawon@gmail.com">
                        aviramjeeawon@gmail.com</a>
                  </li>
                  <li>
                     <i class="icon-phone icomoon"></i>
                     <a href="tel:58299495">+230 58269495</a>
                  </li>
                  <li>
                     <i class="fas fa-globe-asia"></i>
                     <a href="/">home</a>
                  </li>
               </ul>
            </div>
         </div>
      </div>
   </div>
</section>
<!--Footer Content End-->
<!--Footer Copyright Start-->
<section class="tj-copyright">
   <div class="container">
      <div class="row">
         <div class="col-md-4 col-sm-4">
            <p>&copy; Copyrights 2022 <a href="/">Avi Taxi</a>. All Rights Reserved.</p>
         </div>
         <div class="col-md-4 col-sm-4" >
            <p style="float: right;">&#9413; Powered By <a href="#">Avi Pvt Ltd</a>. </p>
         </div>
         <div class="col-md-4 col-sm-4" >
            <p style="float: right;"> Developed By <a href="#">Team Tire - Plan</a>. </p>
         </div>
      </div>
   </div>
</section>
<!--Footer Copyright End-->

car_env/templates/login.html
{% extends 'base.html'%}
{% load static %}

{% block content %}
<style type="text/css">
   .login-icon{
   height: 44px; 
   /*font-weight: bolder;*/ 
   vertical-align: text-bottom;
   }
   .field-icon {
   float: right;
   margin-top: -47px;
   position: relative;
   z-index: 2;
   margin-right: 8px;
   }
</style>
<!--Wrapper Content Start-->
<div class="tj-wrapper">
   <!--Login Section Start-->
   <section class="tj-login">
      <div class="container">
         <div class="row">
            <div class="col-md-12 col-sm-12">
               <!--Tabs Nav Start-->
               <div class="tj-tabs">
                  <ul class="nav nav-tabs" role="tablist">
                     <li class="active"><a href="#login" data-toggle="tab">Login</a></li>
                     <li><a href="#register" data-toggle="tab">Register</a></li>
                  </ul>
               </div>
               <!--Tabs Nav End-->
               <!--Tabs Content Start-->
               <div class="tab-content">
                  <!--Login Tabs Content Start-->
                  <div class="tab-pane active" id="login">
                     <div class="col-md-6 col-sm-6">
                        <!--Register Tabs Form Start-->
                        <form class="reg-frm" method="POST">
                           {% csrf_token %}
                           <input type="hidden" name="type" value="login">
                           <div class="field-holder">
                              <span style="position: absolute;
                                 top: 18px;left: 12px;color: #a6a6a6;font-size: 13px;" class="icon-phone icomoon"></span>
                              <input type="text" name="phone_num" placeholder="Mobile Number" pattern="[5-9]{1}[0-9]{9}" required>
                           </div>
                           <div class="field-holder">
                              <span class="fas fa-lock"></span>
                              <input type="password" name="password" id="password-field" placeholder="Password" required>
                              <span toggle="#password-field" class="fa fa-fw fa-eye field-icon toggle-password"><span class="tooltiptext">Click to see password</span> </span>
                              <a href="{% url 'core:forgot_password' %}"><b>Forgot Password ?</b></a>
                           </div>
                           <br>
                           <button type="submit" class="reg-btn">Login<i class="fa fa-arrow-circle-right" aria-hidden="true"></i></button>
                        </form>
                        <!--Register Tabs Form End-->
                     </div>
                     <div class="col-md-6 col-sm-6">
                        <div class="login-cta">
                           <ul class="cta-list">
                              <li>
                                 <span class="icon"><img class="login-icon" src="{% static 'images/icons/Best-Price-Guranteed.png' %}" alt="" ></span>
                                 <div class="cta-info">
                                    <strong>Best Price Guaranteed</strong>
                                    <p>Assure to give best price for services we offer.</p>
                                 </div>
                              </li>
                              <li>
                                 <span class="icon"><img class="login-icon" src="{% static 'images/icons/instant-booking.png' %}" alt="" ></span>
                                 <div class="cta-info">
                                    <strong>Instant Booking</strong>
                                    <p>Provides instant booking to plan outstation travel anytime.</p>
                                 </div>
                              </li>
                              <li>
                                 <span class="icon"><img class="login-icon" src="{% static 'images/icons/customer-care.png' %}" alt="" ></span>
                                 <div class="cta-info">
                                    <strong>24/7 Customer Care</strong>
                                    <p>Round the clock assistance to ensure hassle free service.</p>
                                 </div>
                              </li>
                              <li>
                                 <span class="icon"><img class="login-icon" src="{% static 'images/icons/home-pickups.png' %}" alt="" ></span>
                                 <div class="cta-info">
                                    <strong>Home Pickups</strong>
                                    <p>Home pick up services, no need to walk out for taxi.</p>
                                 </div>
                              </li>
                              <li>
                                 <span class="icon"><img class="login-icon" src="{% static 'images/icons/easy-cancelation.png' %}" alt=""></span>
                                 <div class="cta-info">
                                    <strong>Easy Cancellation</strong>
                                    <p>Convenient cancellation in case change in plan.</p>
                                 </div>
                              </li>
                           </ul>
                        </div>
                     </div>
                  </div>
                  <!--Login Tabs Content End-->
                  <!--Register Tabs Content Start-->
                  <div class="tab-pane" id="register">
                     <div class="col-md-6 col-sm-6">
                        <!--Register Tabs Form Start-->
                        <form class="reg-frm" method="POST">
                           {% csrf_token %}
                           <input type="hidden" name="type" value="register">
                           <div class="field-holder">
                              <span class="far fa-user"></span>
                              <input type="text" name="full_name" placeholder="Full Name" required>
                           </div>
                           <div class="field-holder">
                              <span style="position: absolute;top: 18px;left: 12px;color: #a6a6a6;font-size: 13px;" class="icon-phone icomoon"></span>
                              <input type="text" name="phone_num" placeholder="Mobile Number" pattern="[5]{1}[0-9]{7}" required>
                           </div>
                           <div class="field-holder">
                              <span class="far fa-envelope"></span>
                              <input type="email" name="email_id" placeholder="Enter your Email Address" required>
                           </div>
                           <div class="field-holder">
                              <span class="fas fa-lock"></span>
                              <input type="password" id="pass" name="password" placeholder="Choose your password" required>
                              <span toggle="#pass" class="fa fa-fw fa-eye field-icon toggle-password"><span class="tooltiptext">Click to see password</span></span>
                              <label id="password_strength" style="font-weight:600;padding-left: 30px;">&nbsp; </label>
                           </div>
                           <label for="terms">
                           <input type="checkbox" name="terms" id="terms" required>
                           I accept <a href="{% url 'core:terms&conditions' %}"> terms & conditions </a>
                           </label>
                           <button type="submit" class="reg-btn">Signup <i class="fa fa-arrow-circle-right" aria-hidden="true"></i></button>
                        </form>
                        <!--Register Tabs Form End-->
                     </div>
                     <div class="col-md-6 col-sm-6">
                        <div class="login-cta">
                           <ul class="cta-list">
                              <li>
                                 <span class="icon"><img class="login-icon" src="{% static 'images/icons/Best-Price-Guranteed.png' %}" alt="" ></span>
                                 <div class="cta-info">
                                    <strong>Best Price Guaranteed</strong>
                                    <p>Assure to give best price for services we offer.</p>
                                 </div>
                              </li>
                              <li>
                                 <span class="icon"><img class="login-icon" src="{% static 'images/icons/instant-booking.png' %}" alt="" ></span>
                                 <div class="cta-info">
                                    <strong>Instant Booking</strong>
                                    <p>Provides instant booking to plan outstation travel anytime.</p>
                                 </div>
                              </li>
                              <li>
                                 <span class="icon"><img class="login-icon" src="{% static 'images/icons/customer-care.png' %}" alt="" ></span>
                                 <div class="cta-info">
                                    <strong>24/7 Customer Care</strong>
                                    <p>Round the clock assistance to ensure hassle free service.</p>
                                 </div>
                              </li>
                              <li>
                                 <span class="icon"><img class="login-icon" src="{% static 'images/icons/home-pickups.png' %}" alt="" ></span>
                                 <div class="cta-info">
                                    <strong>Home Pickups</strong>
                                    <p>Home pick up services, no need to walk out for taxi.</p>
                                 </div>
                              </li>
                              <li>
                                 <span class="icon"><img class="login-icon" src="{% static 'images/icons/easy-cancelation.png' %}" alt=""></span>
                                 <div class="cta-info">
                                    <strong>Easy Cancellation</strong>
                                    <p>Convenient cancellation in case change in plan.</p>
                                 </div>
                              </li>
                           </ul>
                        </div>
                     </div>
                  </div>
                  <!--Register Tabs Content End-->
               </div>
               <!--Tabs Content End-->
            </div>
         </div>
      </div>
   </section>
   <!--Login Section End-->
</div>
<!--Wrapper Content End-->
{% endblock content %}
{% block extra_scripts %}
<script type="text/javascript">
   $(function () {
       $("#pass").bind("keyup", function () {
           //TextBox left blank.
           if ($(this).val().length == 0) {
               $("#password_strength").html("");
               return;
           }
   
           //Regular Expressions.
           var regex = new Array();
           regex.push("[A-Z]"); //Uppercase Alphabet.
           regex.push("[a-z]"); //Lowercase Alphabet.
           regex.push("[0-9]"); //Digit.
           regex.push("[$@$!%*#?&]"); //Special Character.
   
           var passed = 0;
   
           //Validate for each Regular Expression.
           for (var i = 0; i < regex.length; i++) {
               if (new RegExp(regex[i]).test($(this).val())) {
                   passed++;
               }
           }
   
   
           //Validate for length of Password.
           if (passed > 2 && $(this).val().length > 8) {
               passed++;
           }
           console.log(passed)
           //Display status.
           var color = "";
           var strength = "";
           switch (passed) {
               case 0:
               case 1:
                   strength = "Weak";
                   color = "red";
                   break;
               case 2:
                   strength = "Good";
                   color = "darkorange";
                   break;
               case 3:
               case 4:
                   strength = "Strong";
                   color = "green";
                   break;
               case 5:
                   strength = "Very Strong";
                   color = "darkgreen";
                   break;
           }
           $("#password_strength").html(strength);
           $("#password_strength").css("color", color);
       });
   });
</script>
<script type="text/javascript">
   $(".toggle-password").click(function() {
   
    $(this).toggleClass("fa-eye fa-eye-slash");
    var input = $($(this).attr("toggle"));
    if (input.attr("type") == "password") {
      input.attr("type", "text");
    } else {
      input.attr("type", "password");
    }
   });
</script>
<script language="JavaScript">
   var frmvalidator  = new Validator("contactform");
   frmvalidator.addValidation("name","req","Please provide your name");
   frmvalidator.addValidation("email","req","Please provide your email");
   frmvalidator.addValidation("email","email",
     "Please enter a valid email address");
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
{% endblock extra_scripts %}