car_env/blog/urls.py
from django.urls import path
from .views import BlogHomeView, BlogPostView

app_name = 'blog'

urlpatterns = [
    path('', BlogHomeView, name='home'),
    path('<int:id>', BlogPostView, name='post'),
]

car_env/customadmin/urls.py
from django.urls import path
from . import views

app_name = 'customadmin'

urlpatterns = [
    path('', views.HomeView, name='home'),

    # Main Page Urls
    path('general/', views.GeneralModelsView, name='general'),
    path('cities/update/', views.UpdateCityView, name='cities_update'),
    path('testimonial/add/', views.AddTestimonialView, name='testimonial_add'),
    path('testimonial/edit/<int:id>/', views.EditTestimonialView, name='testimonial_edit'),
    path('testimonial/delete/<int:id>/', views.DeleteTestimonialView, name='testimonial_delete'),
    path('home-page-banners/add/', views.AddMainPageBannersView, name='banner_add'),
    path('home-page-banners/edit/<int:id>/', views.EditMainPageBannersView, name='banner_edit'),
    path('home-page-banners/delete/<int:id>/', views.DeleteMainPageBannersView, name='banner_delete'),
    path('update-faqs/', views.UpdateFAQsView, name='update_faqs'),
    path('update-t&c/', views.UpdateTermsAndConditionsView, name='update_tnc'),

    path('contact-us/', views.ContactUsView, name='contact_us'),
    path('payments/', views.PaymentsView, name='payments'),

    # Ride Bookings Urls
    path('cancelled-rides/', views.CancelledRidesView, name='cancelled_rides'),
    path('booked-rides/', views.BookedRidesView, name='booked_rides'),
    path('assign-vendor-rides/', views.AssignVendorRidesView, name='assign_vendor_rides'),
    path('upcoming-rides/', views.UpcomingRidesView, name='upcoming_rides'),
    path('ongoing-rides/', views.OngoingRidesView, name='ongoing_rides'),
    path('completed-rides/', views.CompletedRidesView, name='completed_rides'),
    path('user-cancelled-rides/', views.UserCancelledRides, name='user_cancelled_rides'),
    path('vendor-cancelled-rides/', views.UserCancelledRides, name='vendor_cancelled_rides'),

    path('assign-vendors/<int:id>/', views.AssignVendorsView, name='assign_vendors'),
    path('vendor-bids/<int:id>/', views.UpdateVendorBidsView, name='vendor_bids'),
    path('assign-final-vendor/<int:id>/', views.AssignFinalVendorView, name='assign_final_vendor'),
    path('assign-driver-car/<int:id>/', views.AssignDriverCarView, name='assign_driver_car'),
    path('start-ride/<int:id>/', views.StartRideView, name='start_ride'),
    path('end-ride/<int:id>/', views.EndRideView, name='end_ride'),
    path('verify-ride/<int:id>/', views.VerifyRideView, name='verify_ride'),

    path('final-ride-details/', views.FinalRideDetailsView, name='final_ride_details'),

    # Popular Destinations Urls
    path('popular-destinations/', views.PopularDestinationsView, name = 'popular_destinations'),
    path('popular-destinations/add/', views.AddPopularDestinationView, name = 'popular_destinations_add'),
    path('popular-destinations/edit/<int:id>/', views.EditPopularDestinationView, name = 'popular_destinations_edit'),
    path('popular-destinations/delete/<int:id>/', views.DeletePopularDestinationView, name = 'popular_destinations_delete'),

    # Car Type Urls
    path('car-type/', views.CarTypePageViews, name='car_type'),
    path('update-car-attributes/', views.UpdateCarAttributes, name='update_car_attributes'),
    path('update-car-attribute-values/', views.UpdateCarAttributeValueView, name='update_car_attribute_values'),
    path('update-ride-additional-choices/', views.UpdateRideAdditionalChoices, name='update_ride_additional_choices'),
    path('update-city-ride-attributes/', views.UpdateCityRideAttributeValues, name='update_city_ride_attributes'),

    # Blog Urls
    path('blogs/',views.BlogsView, name="blogs"),
    path('update-categories/', views.UpdateBlogCategoriesView, name="update_categories"),
    path('post/add/',views.AddBlogPostView, name="post_add"),
    path('post/edit/<int:id>/',views.EditBlogPostView, name="post_edit"),
    path('post/delete/<int:id>/',views.DeleteBlogPostView, name="post_delete"),
    path('post/delete-comment/<int:id>/',views.DeleteBlogPostCommentView, name="post_comment_delete"),

    # Customer Urls
    path('customers/',views.CustomersView, name="customers"),
    path('customers/add/',views.AddCustomerView, name="customer_add"),
    path('customers/edit/<int:id>/',views.EditCustomerView, name="customer_edit"),
    path('customers/delete/<int:id>/',views.DeleteCustomerView, name="customer_delete"),

    path('promotional/update/<int:id>/', views.UpdateCustomerPromotionalView, name="customer_update_promotional"),

    # Vendor Urls
    path('vendors/',views.VendorsView, name="vendors"),
    path('vendor/<int:id>/',views.VendorView, name="vendor"),
    path('vendor/add/',views.VendorsView, name="vendor_add"),
    path('vendor/update-status/<int:id>/',views.UpdateVendorStatusView, name="vendor_update_status"),
    path('vendor/edit/<int:id>/',views.EditVendorView, name="vendor_edit"),
    path('vendor/delete/<int:id>/',views.DeleteVendorView, name="vendor_delete"),
    # path('vendor/cars/update/<int:id>/', views.UpdateVendorCarsView, name="vendor_cars_update"),
    # path('vendor/drivers/update/<int:id>/', views.UpdateVendorDriversView, name="vendor_drivers_update"),
    path('vendor/bank-details/update/<int:id>/', views.UpdateVendorBankDetailsView, name="vendor_banks_update"),
    path('vendor/car/add/<int:id>/', views.AddVendorCarView, name="vendor_car_add"),
    path('vendor/car/edit/<int:id>/', views.EditVendorCarView, name="vendor_car_edit"),
    path('vendor/car/delete/<int:id>/', views.DeleteVendorCarView, name="vendor_car_delete"),
    path('vendor/driver/add/<int:id>/', views.AddVendorDriver, name="vendor_driver_add"),
    path('vendor/driver/edit/<int:id>/', views.EditVendorDriver, name="vendor_driver_edit"),
    path('vendor/driver/delete/<int:id>/', views.DeleteVendorDriver, name="vendor_driver_delete"),

    # Test Views
    path('test/1/', views.TestView1, name='test1'),
    path('test/2/', views.TestView2, name='test2'),
    path('test/3/', views.TestView3, name='test3'),
    path('test/4/', views.TestView4, name='test4'),
    path('test/5/', views.TestView5, name='test5'),
    path('dashboard/', views.DashboardView , name='dashboard'),
    path('assign-vendors/<int:id>/', views.AssignVendorsView , name='assign_vendor'),
    path('assign-final-vendor/<int:id>/', views.AssignFinalVendorView , name='assign_final_vendor'),
]

car_env/taxotaxi/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('vendor/', include('vendor.urls', namespace='vendor')),
    path('driver/', include('driver.urls', namespace='driver')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('custom-admin/', include('customadmin.urls', namespace='customadmin')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

car_env/blog/models.py
from django.db import models
from django.conf import settings
from core.models import User
# Create your models here.
from django.shortcuts import get_object_or_404
from vendor import models as vendormodels


class categories(models.Model):
    title = models.CharField(max_length = 100)
    keywords = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Categories'

class post(models.Model):
    title = models.CharField(max_length = 200)
    category = models.ForeignKey(categories, on_delete=models.CASCADE)
    content = models.TextField()
    date = models.DateField()
    published = models.BooleanField(default=1)
    main_image = models.ImageField()
    views = models.IntegerField(default=0)
    image1 = models.ImageField(blank=True, null=True)
    image2 = models.ImageField(blank=True, null=True)
    image3 = models.ImageField(blank=True, null=True)
    image4 = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-date',)
        
    def get_short_content(self):
        if len(self.content) > 500:
            short_content = self.content[:500]
            short_content += "..."
            return short_content
        return self.content


    def get_shortest_content(self):
        if len(self.content) > 200:
            short_content = self.content[:200]
            short_content += "..."
            return short_content
        return self.content

    def count_likes(self):
        count = like.objects.filter(post = self).count()
        return count

    def count_comments(self):
        count = comment.objects.filter(post = self).count()
        return count

class comment(models.Model):
    post = models.ForeignKey(post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    comment_text = models.TextField()

    def __str__(self):
        return self.comment_text

    def get_username(self):
        if self.user.is_vendor:
            username = get_object_or_404(vendormodels.vendorprofile, user=self.user).full_name
        else:
            username = self.user.get_full_name()
        return username

    def get_profileimage(self):
        if self.user.is_vendor:
            profileimage = get_object_or_404(vendormodels.vendorprofile, user=self.user).image
            return profileimage.url
        else:
            profileimage = self.user.profile_pic
            if profileimage:
                return profileimage.url
        profileimage = 'http://placehold.it/50x50'
        return profileimage

class like(models.Model):
    post = models.ForeignKey(post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

car_env/customadmin/models.py
from django.db import models

# Create your models here.

car_env/blog/forms.py
from django import forms

class CommentForm(forms.Form):
    comment_text = forms.CharField(widget = forms.Textarea(attrs={'class':"form-control", 'rows':"3"}))

car_env/customer/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone

from . import models, forms
import requests
from django.contrib.auth import authenticate, login, logout
from rest_framework.status import HTTP_200_OK, HTTP_400_BAD_REQUEST
from core import models as coremodels
from core import forms as coreforms
from core.payu import PAYU
payu = PAYU()


@login_required(login_url='/login/')
def DashboardView(request):
    try:
        customerprofile = models.customerprofile.objects.get(user = request.user)
    except:
        customerprofile = None

    if request.method == 'POST':
        type = request.POST['type']
        print(request.POST)
        if type == 'profile':


            form = forms.CustomerProfileForm(request.POST, request.FILES, instance=customerprofile)
            userform = coreforms.UserProfileForm(request.POST, request.FILES, instance=request.user)

            if form.is_valid() and userform.is_valid():
                new_form = form.save(commit=False)
                new_form.user = request.user
                new_form.save()

                userform.save()
                messages.success(request, 'Details Saved Successfully',  extra_tags='alert alert-success alert-dismissible')
                return redirect('customer:dashboard')

            return redirect('customer:dashboard')

        elif type == 'change_password':
            password = request.POST['current_password']
            new_password = request.POST['new_password']
            user = authenticate(username = request.user.username, password = password)
            if user is not None:
                user.set_password(new_password)
                user.save()
                login(request, user)

                messages.success(request, 'Password Updated',  extra_tags='alert alert-success alert-dismissible')
                return redirect('customer:dashboard')
            else:
                messages.error(request, 'Invalid Password',  extra_tags='alert alert-danger alert-dismissible')
                return redirect('customer:dashboard')

        return redirect('customer:dashboard')


    else:
        payments = coremodels.payment.objects.filter(booking__user=request.user)

        upcoming_rides = coremodels.ride_booking.objects.filter(user=request.user).exclude(ride_status__in = ['Cancelled', 'Verified', "User Cancelled"])
        cancelled_rides = coremodels.ride_booking.objects.filter(user=request.user, ride_status='User Cancelled')
        incomplete_rides = coremodels.ride_booking.objects.filter(user=request.user, ride_status='Cancelled')
        completed_rides = coremodels.ride_booking.objects.filter(user=request.user, ride_status='Verified')

        try:
            referral_codes = coremodels.user_referral.objects.filter(user=request.user, is_activated=True)
        except:
            referral_codes = None

        user = coremodels.User.objects.get(username = request.user.username)
        userform = coreforms.UserProfileForm(instance = user)
        profileform = forms.CustomerProfileForm(instance=customerprofile)
        context = {
            'profileform':profileform,
            'userform':userform,
            'referral_codes':referral_codes,

            'upcoming_rides':upcoming_rides,
            'cancelled_rides':cancelled_rides,
            'completed_rides':completed_rides,
            'incomplete_rides':incomplete_rides,
        }
        return render(request, 'Customer Dashboard/customer_dashboard.html', context)

def CustomerFeedback(request):
    if request.method == "POST":
        final_ride_id = request.POST.get('final_ride_id')
        comment = request.POST.get('comment')
        feedback = request.POST.getlist("feedback")
        total = 6
        avg = len(feedback)/total
        final_ride = get_object_or_404(coremodels.final_ride_detail, id=final_ride_id)
        final_ride.review = comment
        final_ride.rating = avg
        final_ride.save()
        return HttpResponse({"Status": "Feedback Submitted Successfuly!"}, status = HTTP_200_OK)

def CancelRideView(request, id):
    booking = get_object_or_404(coremodels.ride_booking, id=id)
    booking.ride_status = 'User Cancelled'
    booking.save()
    return redirect('customer:dashboard')

def CompletePayment(request, id):
    booking = get_object_or_404(coremodels.ride_booking, id=id)
    data = {
        'txnid': payu.generate_txnid(), 'amount': str(int(booking.advance)), 'productinfo': str(booking.ride_type),
        'firstname': str(request.user.first_name), 'email': str(request.user.email), 'udf1': str(booking.id),
    }
    # print(data)
    payu_data = payu.initiate_transaction(data)
    print('--------------------PAYMENT VIEW Rendering ----------------------------')
    return render(request, 'payments/payu_checkout.html', {"posted": payu_data})


'''

@login_required(login_url='/login/')
def RegistrationView(request):
    if request.method == 'POST':
        form = forms.CustomerProfileForm(request.POST, request.FILES)
        print(form.errors)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user  =request.user
            new_form.save()
            return redirect('customer:dashboard')
        return redirect('customer:dashboard')
    else:
        form = forms.CustomerProfileForm()
        context = {
            'form':form,
        }
        return render(request, 'vendor_form.html' ,context)
'''

car_env/customadmin/templates/blogs/categories_formset.html
{% extends 'admin_base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block extra_stylesheet %}

{% endblock extra_stylesheet %}



{% block content %}

<div class="main-content">

    <div class="page-content">
        <div class="container-fluid">

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box d-flex align-items-center justify-content-between">
                        <h4 class="mb-0 font-size-18">Blog Categories Form</h4>

                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="javascript: void(0);">Blogs</a></li>
                                <li class="breadcrumb-item active">Blog Categories Form</li>
                            </ol>
                        </div>

                    </div>
                </div>
            </div>
            <!-- end page title -->

            <div class="row">
            <div class="col-12">
                    <div class="card">
                        <div class="card-body">

                            <h4 class="card-title"></h4>
                            <p class="card-title-desc"></p>
                            <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ formset.management_form }}
                                <div data-repeater-list="group-a" id="form_set">
                                    {% for form in formset %}
                                    <div data-repeater-item="" class="row">
                                        <div class="form-group col-lg-4">
                                            <label for="name">Title</label>
                                            {% render_field form.title class="form-control" %}
                                        </div>
                                        <div class="form-group col-lg-6">
                                            <label for="name">Keywords</label>
                                            {% render_field form.keywords class="form-control" rows="2" %}
                                        </div>
                                        <div class="form-group col-lg-2">
                                            <label for="name">Delete</label>
                                            {% render_field form.DELETE class="form-control" %}
                                        </div>

                                        {% for field in form.hidden_fields %}
                                            {{ field }}
                                        {% endfor %}
                                    {{ form.errors }}
                                    </div>

                                    {% endfor %}
                                </div>
                            <input data-repeater-create="" type="button" class="btn btn-warning mt-3 mt-lg-0" value="Add" id="add_more">
                            <input type="submit" class="btn btn-success mt-3 mt-lg-0" value="Save">

                            </form>
                        </div>
                    </div>
            </div>

                <div hidden id="empty_form">
                    <div data-repeater-item="" class="row">
                        <div class="form-group col-lg-4">
                            <label for="name">Title</label>
                            {% render_field formset.empty_form.title class="form-control" %}
                        </div>
                        <div class="form-group col-lg-6">
                            <label for="name">Keywords</label>
                            {% render_field formset.empty_form.keywords class="form-control" rows="2" %}
                        </div>
                        <div class="form-group col-lg-2">
                            <label for="name">Delete</label>
                            {% render_field formset.empty_form.DELETE class="form-control" %}
                        </div>
                        {% for field in formset.empty_form.hidden_fields %}
                            {{ field }}
                        {% endfor %}
                        {{  formset.empty_form.errors }}
                    </div>
                </div>
            </div>
            <!-- end row -->

            <!-- end row -->

        </div> <!-- container-fluid -->
    </div>
    <!-- End Page-content -->



</div>

{% endblock content %}




{% block extra_scripts %}
<script>
    $('#add_more').click(function() {
        var form_idx = $('#id_form-TOTAL_FORMS').val();
        console.log(form_idx);
        $('#form_set').append($('#empty_form').html().replace(/__prefix__/g, form_idx));
        $('#id_form-TOTAL_FORMS').val(parseInt(form_idx) + 1);
    });

    $( document ).ready(function() {
        $( "input[name*='date']" ).datepicker({
              dateFormat: 'yy-mm-dd',
              minDate: 0,
        });
    });
</script>
{% endblock extra_scripts %}

car_env/customadmin/templates/blogs/index.html
{% extends 'admin_base.html' %}
{% load static %}


{% block extra_stylesheet %}

{% endblock extra_stylesheet %}



{% block content %}
<div class="main-content">

    <div class="page-content">
        <div class="container-fluid">

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box d-flex align-items-center justify-content-between">
                        <h4 class="mb-0 font-size-18">Blog Tables</h4>

                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="javascript: void(0);">Tables</a></li>
                                <li class="breadcrumb-item active">Blog Tables</li>
                            </ol>
                        </div>

                    </div>
                </div>
            </div>
            <!-- end page title -->

            {% comment %}
            <button type="button" class="btn btn-success waves-effect waves-light mb-3">
                <i class="bx bx-add-to-queue font-size-16 align-middle mr-2"></i> Add
            </button>
            {% endcomment %}
            <div class="row">
                <div class="col-3">
                    <div class="card">
                        <div class="card-body">

                            <h4 class="card-title">
                                Category
                                <a href="{% url 'customadmin:update_categories' %}">
                                <button type="button" style="float: right;" class="btn btn-success waves-effect waves-light mb-2">
                                    <i class="bx bx-add-to-queue font-size-16 align-middle"></i> Update
                                </button></a>
                            </h4>
                            <p class="card-title-desc">
                            </p>
                            <div class="table-responsive">
                                <table id="" class="table table-striped table-bordered nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100% !important;">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Category</th>
                                </tr>
                                </thead>

                                <tbody>
                                {% for category in categories %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ categroy.title }}</td>
                                </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                        </div>
                        </div>
                    </div>
                </div> <!-- end col -->

                {% for category in categories %}
                <div class="col-9">
                    <div class="card">
                        <div class="card-body">

                            <h4 class="card-title">Posts
                                <a href="{% url 'customadmin:post_add' %}">
                                 <button type="button" style="float: right;" class="btn btn-success waves-effect waves-light mb-2">
                                    <i class="bx bx-add-to-queue font-size-16 align-middle"></i> Add
                                 </button>
                                    </a>

                            </h4>
                            <p class="card-title-desc">
                            </p>
                            <div class="table-responsive">
                                <table id="" class="table table-striped table-bordered nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100% !important;">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Title</th>
                                    <th>Date</th>
                                    <th>Published</th>
                                    <th>Likes</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>


                                <tbody>
                                {% for post in category.post_set.all %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ post.title }}</td>
                                        <td>{{ post.date }}</td>
                                        <td>{% if post.published %}<i class="bx bx-select-multiple font-size-16 align-middle mr-2"></i>{% endif %}</td>
                                        <td>{{ post.count_likes }}</td>
                                        <td>
                                            <a href="{% url 'customadmin:post_edit' post.id %}">
                                            <i class="bx bx-edit-alt font-size-16 align-middle"></i></a>
                                            <a href="{% url 'customadmin:post_delete' post.id %}">
                                            <i class="bx bxs-trash font-size-16 align-middle"></i></a>
                                       </td>
                                    </tr>
                                {% endfor %}
                         
                              
                                </tbody>
                            </table>
                        </div>
                        </div>
                    </div>
                </div>
                <!-- end col -->
                {% endfor %}
            </div> <!-- end row -->

        {% for category in categories %}
            {% for post in category.post_set.all %}
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">

                                <h4 class="card-title"> Comments <button type="button" style="float: right;" class="btn btn-success waves-effect waves-light mb-2">
                                    <i class="bx bx-add-to-queue font-size-16 align-middle"></i> Add
                                </button></h4>
                                <p class="card-title-desc">
                                </p>
                                <div class="table-responsive">
                                    <table id="" class="table table-striped table-bordered nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100% !important;">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>User Name</th>
                                        <th>Comment</th>
                                        <th>Action</th>
                                    </tr>
                                    </thead>


                                    <tbody>
                                    {% for comment in post.comment_set.all %}
                                        <tr>
                                            <td>{{ forloop.counter }}</td>
                                            <td>{{ comment.name }}</td>
                                            <td>{{ comment.comment_text }}</td>
                                            <td>
                                                <a href="{% url 'customadmin:post_comment_delete' post.id %}">
                                                    <i class="bx bxs-trash font-size-16 align-middle"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    {% endfor %}


                                    </tbody>
                                </table>
                            </div>
                            </div>
                        </div>
                    </div>
                </div>
               <!-- end row -->
            {% endfor %}
        {% endfor %}
        </div> <!-- container-fluid -->
    </div>
    <!-- End Page-content -->

   
</div>

{% endblock content %}




{% block extra_scripts %}

{% endblock extra_scripts %}